version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: jaga/app
    volumes:
     - .:/var/www/html
    networks:
     - tbnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: jaga/node
    volumes:
     - .:/var/www/html
    networks:
     - tbnet
  mysql:
    image: mysql:5.7
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - tbnet
  chrome:
    image: selenium/standalone-chrome
    volumes:
     - .:/var/www/html
    networks:
     - tbnet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - tbnet